In [ ]:
!pip install tabula-py

Collecting tabula-py
  Downloading https://files.pythonhosted.org/packages/cf/29/d6cb0d77ef46d84d35cffa09cf42c73b373aea664d28604eab6818f8a47c/tabula_py-2.2.0-py3-none-any.whl (11.7MB)
     |████████████████████████████████| 11.7MB 3.6MB/s
Collecting distro
  Downloading https://files.pythonhosted.org/packages/25/b7/b3c4270a11414cb22c6352ebc7a83aaa3712043be29daa05018fd5a5c956/distro-1.5.0-py2.py3-none-any.whl
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from tabula-py) (1.18.5)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.6/dist-packages (from tabula-py) (1.1.4)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.25.3->tabula-py) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.25.3->tabula-py) (2.8.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.7.3->pandas>=0.25.3->tabula-py) (1.15.0)
Installing collected packages: distro, tabula-py
Successfully installed distro-1.5.0 tabula-py-2.2.0

In [ ]:
import tabula
import pandas as pd
from google.colab import files

#Definir la ruta del PDF

pdf_ruta="https://github.com/josejparra/Diplomado-UNAL/raw/main/PreciosAgro2017.pdf"

In [ ]:
#Corregir ceros

def chequeo(x):
  if not isinstance(x,str) and x<100:
    return x*1000
  else:
    return x

In [ ]:
#Lectura del PDF usando ambos sistemas.

pag_l2 = tabula.read_pdf(pdf_ruta,pages="all",encoding="utf-8",pandas_options={'header': None},lattice=True)
pag_s2 = tabula.read_pdf(pdf_ruta,pages="all",encoding="utf-8",pandas_options={'header': None},stream=True)

In [ ]:
#Nombres de los productos

nombres=["ACELGA","AGRAZ","AGUACATE","AGUACATE HASS",
         "p","AGUACATE HASS","AGUACATE LORENA","AHUYAMA","AJI",
         "p","AJO","APIO","ARRACACHA","ARROZ TECNIFICADO","ARROZ TRADICIONAL",
         "p","ARROZ TRADICIONAL","ARVEJA","BANANO CRIOLLO","BANANO MANZANO",
         "p","BANANO MONOCULTIVO","BOROJO","BREVO","BROCOLI","CACAO",
         "p","CACAO",
         "p","CAFE",
         "p","CAFE","CALABACÍN","PANELA",
         "p","PANELA",
         "p","PANELA","CARDAMOMO","CAUCHO","CEBOLLA DE HUEVO",
         "p","CEBOLLA JUNCA","CEBOLLIN","CHOCOLO","COCO",
         "p","CILANTRO","COL","COLIFLOR","CURCUMA","FIQUE",
         "p","ESPINACA","FRESA","FRIJOL ARBUSTIVO",
         "p","FRIJOL ARBUSTIVO","FRIJOL VERDE","FRIJOL VOLUBLE",
         "p","FRIJOL VOLUBLE","GRANADILLA",
         "p","GUANABANA","GUAYABA","GUAYABA MANZANA","GULUPA","HIGO",
         "p","HABICHUELA","HORTALIZAS VARIAS","LECHUGA","LIMA ACIDA TAHITI",
         "p","LIMON MANDARINO","LIMON PAJARITO","LULO",
         "p","MAIZ",
         "p","MAIZ","MAIZ FORRAJERO","MANDARINA CLEMENTINA",
         "p","MANDARINA ONECO","MANGO COMÚN","MANGO INJERTO","MARACUYA",
         "p","MARACUYA","MORA","MURRAPO","NARANJA TANGELO MINEOLA",
         "p","NARANJA COMÚN","NARANJA JAFFA","NARANJA TANGELO ORLANDO","NARANJA VALENCIA","NARANJA WASHINGTON NAVEL","NARANJA SALUSTIANA",
         "p","ÑAME","PALMA DE ACEITE","PAPA",
         "p","PAPA CRIOLLA","PAPAYA","PEPINO","PIMENTON","PIÑA",
         "p","PLANTAS AROMATICAS","PLATANO EN ASOCIO",
         "p","PLATANO EN ASOCIO","PLATANO MONOCULTIVO",
         "p","PLATANO MONOCULTIVO","REMOLACHA","REPOLLO","SACHA INCHI","STEVIA",
         "p","TOMATE CHONTO","TOMATE CHONTO INVERNADERO",
         "p","TOMATE CHONTO INVERNADERO","TOMATE DE ARBOL",
         "p","UCHUVA","YUCA",
         "p","YUCA",
         "p","ZANAHORIA"]

#Selección de lectura usando el sistema más apropiado

productos=pag_l2[1].applymap(chequeo)
productos["producto"]=nombres[0]
for i in range(2,len(pag_l2)):
    if pag_l2[i].iloc[0,0]=="Municipio":
      continue
    elif pag_l2[i].shape[1]==14 and pag_l2[i].iloc[0,0].find("\r")==-1:
        pag_l2[i]=pag_l2[i].applymap(chequeo)
        pag_l2[i]["producto"]=nombres[i-1]
        productos=productos.append(pag_l2[i])
    else:
      pag_s2[i]=pag_s2[i].applymap(chequeo)
      pag_s2[i]["producto"]=nombres[i-1]
      productos=productos.append(pag_s2[i])

In [ ]:
#Añadir columnas que contienen nombres
columnas=pag_l2[0].loc[0,:].tolist()
columnas.append("producto")
productos.columns=columnas

#Verificar que no haya ningún producto con el cambio de página.
productos[productos.producto=="p"]

Empty DataFrame
Columns: [Municipio, Ener., Feb., Mar., Abr., May., Jun., Jul., Agos., Sepb, Oct., Nov., Dicbre, Prom., producto]
Index: []

In [ ]:
#Añadir código municipal del DANE.

divipola_ruta="https://raw.githubusercontent.com/josejparra/Diplomado-UNAL/main/Divipola.csv"

divipola=pd.read_csv(divipola_ruta,encoding="latin-1",sep=";")
divipola.rename(columns={"Municipios":"Municipio"},inplace=True)

divipola.Municipio=divipola.Municipio.replace("Jerico","Jericó")
divipola.Municipio=divipola.Municipio.replace("Cañasgordas","Cañas Gordas")

#Verificar que todos los municipios tengan nombres homogéneos.
divipola.Municipio.unique()

array(['Abejorral', 'Abriaquí', 'Alejandría', 'Amagá', 'Amalfi', 'Andes',
       'Angelópolis', 'Angostura', 'Anorí', 'Anza', 'Apartadó',
       'Arboletes', 'Argelia', 'Armenia', 'Barbosa', 'Bello', 'Belmira',
       'Betania', 'Betulia', 'Briceño', 'Buriticá', 'Cáceres', 'Caicedo',
       'Caldas', 'Campamento', 'Cañas Gordas', 'Caracolí', 'Caramanta',
       'Carepa', 'Carolina del Príncipe', 'Caucasia', 'Chigorodo',
       'Cisneros', 'Ciudad Bolivar', 'Cocorná', 'Concepción', 'Concordia',
       'Copacabana', 'Dabeiba', 'Don Matías', 'Ebéjico', 'El Bagre',
       'El Carmen de V.', 'El Peñol', 'El Retiro', 'El Santuario',
       'Entrerrios', 'Envigado', 'Fredonia', 'Frontino', 'Giraldo',
       'Girardota', 'Gómez Plata', 'Granada', 'Guadalupe', 'Guarne',
       'Guatape', 'Heliconia', 'Hispania', 'Itagüí', 'Ituango', 'Jardín',
       'Jericó', 'La Ceja del Tambo', 'La Estrella', 'La Pintada',
       'La Unión', 'Liborina', 'Maceo', 'Marinilla', 'Medellín',
       'Montebello', 'Murindó', 'Mutatá', 'Nariño', 'Nechí', 'Necoclí',
       'Olaya', 'Peque', 'Pueblo Rico', 'Puerto Berrio', 'Puerto Nare',
       'Puerto Triunfo', 'Remedios', 'Rionegro', 'Sabanalarga',
       'Sabaneta', 'Salgar', 'San Andrés de C.', 'San Carlos',
       'San Francisco', 'San Jerónimo', 'San José de la Montaña',
       'San Juan de Urabá', 'San Luis', 'San Pedro de los M.',
       'San Pedro de Urabá', 'San Rafael', 'San Roque', 'San Vicente',
       'Santa Bárbara', 'Santa Fe de Ant.', 'Santa Rosa de O.',
       'Santo Domingo', 'Segovia', 'Sonsón', 'Sopetrán', 'Támesis',
       'Tarazá', 'Tarso', 'Titiribí', 'Toledo', 'Turbo', 'Uramita',
       'Urrao', 'Valdivia', 'Valparaíso', 'Vegachi', 'Venecia',
       'Vigía del Fuerte', 'Yali', 'Yarumal', 'Yolombó', 'Yondó',
       'Zaragoza'], dtype=object)

In [ ]:
#Unificar nombres.

productos.Municipio=productos.Municipio.replace("Cañasgordas","Cañas Gordas")
productos2=productos.merge(divipola,"left")

productos2

               Municipio   Ener.    Feb.  ...   Prom.   producto  Codigo
0              Marinilla  1550.0  1050.0  ...  1098.0     ACELGA  5440.0
1               Promedio  1550.0  1050.0  ...  1098.0     ACELGA     NaN
2       Santa Rosa de O.  8200.0  8300.0  ...  8055.0      AGRAZ  5686.0
3               Promedio  8200.0  8300.0  ...  8055.0      AGRAZ     NaN
4                Argelia  2000.0  2000.0  ...  2117.0   AGUACATE  5055.0
..                   ...     ...     ...  ...     ...        ...     ...
954            Marinilla   772.0   642.0  ...  1215.0  ZANAHORIA  5440.0
955             Medellín   656.0   631.0  ...   902.0  ZANAHORIA  5001.0
956  San Pedro de los M.     NaN     NaN  ...   608.0  ZANAHORIA  5664.0
957               Sonsón   720.0   700.0  ...   766.0  ZANAHORIA  5756.0
958             Promedio   833.0  1125.0  ...  1024.0  ZANAHORIA     NaN

[959 rows x 16 columns]

In [ ]:
#Eliminar promedios

productos3=productos2[~(productos2.Municipio=="Promedio")]

productos3

               Municipio   Ener.    Feb.  ...   Prom.   producto  Codigo
0              Marinilla  1550.0  1050.0  ...  1098.0     ACELGA  5440.0
2       Santa Rosa de O.  8200.0  8300.0  ...  8055.0      AGRAZ  5686.0
4                Argelia  2000.0  2000.0  ...  2117.0   AGUACATE  5055.0
5              Girardota  2500.0  2400.0  ...  2546.0   AGUACATE  5308.0
6                Ituango  2800.0  2800.0  ...  2650.0   AGUACATE  5361.0
..                   ...     ...     ...  ...     ...        ...     ...
953         El Santuario  1017.0  1650.0  ...  1604.0  ZANAHORIA  5697.0
954            Marinilla   772.0   642.0  ...  1215.0  ZANAHORIA  5440.0
955             Medellín   656.0   631.0  ...   902.0  ZANAHORIA  5001.0
956  San Pedro de los M.     NaN     NaN  ...   608.0  ZANAHORIA  5664.0
957               Sonsón   720.0   700.0  ...   766.0  ZANAHORIA  5756.0

[869 rows x 16 columns]

In [ ]:
productos3[productos3.Codigo.isnull()]

productos3.set_index("Codigo",inplace=True)

In [ ]:
from google.colab import files

productos3.to_csv('precios_agro2017.csv',encoding="latin-1")
files.download('precios_agro2017.csv')